### ISSUE TITLE
Random Unexpected token error 

### ISSUE THREAD

**Issue by sochka** [terinjokes/gulp-uglify#111]
Hi, I sometimes randomly (relative rarely) get this error which results in failures of my travis builds. Most of the time there is no problem but sometimes it happens. The file where the error happens is, as I see, the same, but it's content is never changed.
```
[15:46:30] 'JS' components/angular-leaflet/dist/angular-leaflet-directive.js 60.35 kB
Error in plugin 'gulp-uglify'
Message:
    /home/travis/build/kpi-wdc/wdc/.tmp/public/components/es6-module-loader/demo/test1.js: Unexpected token: keyword (var)
Details:
    fileName: /home/travis/build/kpi-wdc/wdc/.tmp/public/components/es6-module-loader/demo/test1.js
    lineNumber: 1
[15:46:30] 'JS' all files 3.07 MB
/home/travis/build/kpi-wdc/wdc/node_modules/gulp-uglify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:972
  for (var i = 0, l = xs.length; i < l; i++) {
                        ^
TypeError: Cannot read property 'length' of null
    at forEach (/home/travis/build/kpi-wdc/wdc/node_modules/gulp-uglify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:972:25)
    at flow (/home/travis/build/kpi-wdc/wdc/node_modules/gulp-uglify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:634:7)
    at DestroyableTransform.<anonymous> (/home/travis/build/kpi-wdc/wdc/node_modules/gulp-uglify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:613:7)
    at DestroyableTransform.emit (events.js:104:17)
    at onwriteDrain (/home/travis/build/kpi-wdc/wdc/node_modules/gulp-size/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:300:12)
    at afterWrite (/home/travis/build/kpi-wdc/wdc/node_modules/gulp-size/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:288:5)
    at onwrite (/home/travis/build/kpi-wdc/wdc/node_modules/gulp-size/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:281:7)
    at WritableState.onwrite (/home/travis/build/kpi-wdc/wdc/node_modules/gulp-size/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:106:5)
    at afterTransform (/home/travis/build/kpi-wdc/wdc/node_modules/gulp-size/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:104:5)
    at TransformState.afterTransform (/home/travis/build/kpi-wdc/wdc/node_modules/gulp-size/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v0.12.4/bin/node" "/home/travis/.nvm/versions/node/v0.12.4/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! .1 postinstall: `jspm install && gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the .1 postinstall script 'jspm install && gulp build'.
npm ERR! This is most likely a problem with the wdc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jspm install && gulp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls wdc
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/kpi-wdc/wdc/npm-debug.log
```

**Comment by terinjokes** [comment]
Interesting, though I've got no ideas.

Do you have a reproducible case?

**Comment by sochka** [comment]
Umh, not now, but if I ever have this problem again - I'll write it here.
