### ISSUE TITLE
Parsing Error with ES6

### ISSUE THREAD

**Issue by marcrd** [terinjokes/gulp-uglify#131]
So working on moving the Bootstrap 4 workflow from Grunt to Gulp. Working on iterating through my JavaScript with Uglify. Come up with this error: 

"[Error: /Users/marcrudkowski/bootstrap4/bootstrap-4.0.0-alpha/dist/js/util.js: Unexpected token: operator (>)" 

**Here's the full stack trace:**

Finished 'default' after 656 ms
[16:48:50] { [Error: /Users/marcrudkowski/bootstrap4/bootstrap-4.0.0-alpha/dist/js/util.js: Unexpected token: operator (>)]
message: '/Users/marcrudkowski/bootstrap4/bootstrap-4.0.0-alpha/dist/js/util.js: Unexpected token: operator (>)',

  fileName: '/Users/marcrudkowski/bootstrap4/bootstrap-4.0.0-alpha/dist/js/util.js',
  lineNumber: 8,
 'Error\n    at new JS_Parse_Error (/Users/marcrudkowski/bootstrap4/bootstrap-4.0.0-alpha/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:196:18)
at js_error (/Users/marcrudkowski/bootstrap4/bootstrap-4.0.0-alpha/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:204:11)
 at croak (/Users/marcrudkowski/bootstrap4/bootstrap-4.0.0-alpha/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:679:41)\n    
at token_error (/Users/marcrudkowski/bootstrap4/bootstrap-4.0.0-alpha/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:683:9)\n   
 at unexpected (/Users/marcrudkowski/bootstrap4/bootstrap-4.0.0-alpha/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:689:9)\n  
at expr_atom (/Users/marcrudkowski/bootstrap4/bootstrap-4.0.0-alpha/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1196:9)\n   
at maybe_unary (/Users/marcrudkowski/bootstrap4/bootstrap-4.0.0-alpha/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1358:19)\n   
at expr_ops (/Users/marcrudkowski/bootstrap4/bootstrap-4.0.0-alpha/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1393:24)\n 
at maybe_conditional (/Users/marcrudkowski/bootstrap4/bootstrap-4.0.0-alpha/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1398:20)\n  
at maybe_assign (/Users/marcrudkowski/bootstrap4/bootstrap-4.0.0-alpha/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1422:20)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uglify' }

**Here's the offending line it is complaining about:**
```"const Util = (($) => { "```

**Here is my gulpfile:**

```javascript
Load Node Modules/Plugins
import gulp from 'gulp';
import gulpLoadPlugins from 'gulp-load-plugins';
import browserSync from 'browser-sync';
import del from 'del';
import concat from 'concat';
var gutil = require('gulp-util');

const reload = browserSync.reload;
const $ = gulpLoadPlugins();

// Remove existing docs and dist build
gulp.task('clean', del.bind(null, ['docs/dist', 'dist']));


// Build CSS files
gulp.task('styles', function() {
  gulp.src('./scss/**/*.scss')
    .pipe($.plumber())
    .pipe($.sourcemaps.init())
    .pipe($.sass().on('error', $.sass.logError))
    .pipe($.autoprefixer({browsers: ['last 1 version']}))
    .pipe($.sourcemaps.write())
    .pipe(gulp.dest('dist/css'))
    .pipe($.rename({ suffix: '.min' }))
    .pipe($.minifyCss())
    .pipe(gulp.dest('dist/css'));
});

// Build JavaScript files 
gulp.task('scripts', function() {
  return gulp.src(['js/src/util.js', 'js/src/alert.js', 'js/src/button.js', 'js/src/carousel.js', 'js/src/collapse.js', 'js/src/dropdown.js', 'js/src/modal.js', 'js/src/scrollspy.js', 'js/src/tab.js', 'js/src/tooltip.js', 'js/src/popover.js'])
    .pipe(gulp.dest('dist/js'))
    .pipe($.uglify().on('error', gutil.log))
    .pipe(gulp.dest('dist/js'));
});

// Watch tasks
gulp.task('watch', function() {     
       gulp.watch('scss/*.scss', ['styles']);
       gulp.watch('js/src/*.js', ['scripts']);
});

gulp.task('dist', ['styles', 'scripts']);

gulp.task('default', ['clean'], () => {
  gulp.start('dist');
}); 
```

I can give the directions to set up the project settings directly if needed :) Just wondering if this was an ES6 issue or not! 

File can be found here: https://github.com/twbs/bootstrap/tree/v4-dev

Under js/dist/util.js

**Comment by terinjokes** [comment]
This is an ES6 issue. Please use [babel](https://babeljs.io) via one of their gulp plugins first.
