### ISSUE TITLE
Bug: errors from uglify are not reported by gulp-uglify

### ISSUE THREAD

**Issue by rogierschouten** [terinjokes/gulp-uglify#136]
Seen in version 1.3.0:   uglify threw an error but in Gulp you don't get to see it. 

Erroneous JS file wrong.js:
```javascript
"use strict";
function render() {
	// note erroneous let
	let upEnabled = true;
	console.log(upEnabled);
}
module.exports = render;
```

gulpfile.js:
```javascript
var gulp = require("gulp");
var uglify = require("gulp-uglify");

gulp.task("default", function() {
	return gulp
		.src("./wrong.js")
		.pipe(uglify())
		.pipe(gulp.dest("./out"));
});
```

Output
```shell
$ gulp
[09:31:56] Using gulpfile c:\Source\eXLent_master\exlent\temp\gulpfile.js
[09:31:56] Starting 'default'...

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error
    at new JS_Parse_Error (c:\Source\eXLent_master\exlent\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:196:18)
    at js_error (c:\Source\eXLent_master\exlent\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:204:11)
    at croak (c:\Source\eXLent_master\exlent\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:684:41)
    at token_error (c:\Source\eXLent_master\exlent\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:688:9)
    at unexpected (c:\Source\eXLent_master\exlent\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:694:9)
    at semicolon (c:\Source\eXLent_master\exlent\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:714:43)
    at simple_statement (c:\Source\eXLent_master\exlent\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:894:73)
    at c:\Source\eXLent_master\exlent\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:767:19
    at c:\Source\eXLent_master\exlent\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:727:24
    at block_ (c:\Source\eXLent_master\exlent\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:1007:20)
```

Actual error, which is not shown:

```shell
{ message: 'Unexpected token: name (upEnabled)',
  filename: '?',
  line: 5,
  col: 5,
  pos: 67,
  stack: 'Error\n    at new JS_Parse_Error (c:\\Source\\eXLent_master\\exlent\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\lib\\parse.js:196:18)\n    at js_error (c:\\Source\\eXLent_master\\exlent\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\lib\\parse.js:204:11)\n    at croak (c:\\Source\\eXLent_master\\exlent\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\lib\\parse.js:684:41)\n    at token_error ....' }
```

**Comment by terinjokes** [comment]
The actual error can be shown if you attach an error handler to the stream,
rather than allowing it to bubble to node's uncaught exception handler.

A couple examples can be found in gulp's "recipe" docs, which I believe are
linked to from gulp-uglify's readme.

**Comment by ktimothy** [comment]
This behavior seems to be weird. Gulp-uglify already throws an error, why not make its message clear?

**Comment by terinjokes** [comment]
The fact that my message isn't being displayed by Node is certainly a bug somewhere. Will follow up with other parties.

**Comment by JordanSinko** [comment]
Not sure if you have resolved this or not, but I had the same issue. This was fixed when I used the 'var' keyword instead of the 'let' keyword. Not sure why this would cause it, but maybe it will help find a resolution.

**Comment by terinjokes** [comment]
The stack trace exhibited here is the documented and expected behavior from Node.js when the errors from streams are not handled.

As a result, I've modified the README to capture errors from streams, so that the more useful error message from this plugin is shown, rather than the stack trace from UglifyJS2.
