### ISSUE TITLE
Unhandled stream error in pipe

### ISSUE THREAD

**Issue by chovy** [terinjokes/gulp-uglify#142]
```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: write after end
    at writeAfterEnd (/Users/me/foo/node_modules/gulp-uglify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:191:12)
    at DestroyableTransform.Writable.write (/Users/me/foo/node_modules/gulp-uglify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:236:5)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:107:17)
    at Stream.endStream (/Users/me/foo/node_modules/gulp-usemin/node_modules/gulp-concat/index.js:90:10)
    at _end (/Users/me/foo/node_modules/gulp-usemin/node_modules/gulp-concat/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/me/foo/node_modules/gulp-usemin/node_modules/gulp-concat/node_modules/through/index.js:74:5)
    at Transform.onend (/Users/me/foo/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Transform.g (events.js:199:16)
    at Transform.emit (events.js:129:20)
```

Using node 12 and here is the gulpfile:

```
gulp.task('default', ['clean'], function() {
    return gulp.src('client/*.html')
        .pipe(usemin({
            css: [ rev() ],
            html: [ minifyHtml({ empty: true }) ],
            js: [ uglify(), rev() ],
            inlinejs: [ uglify() ],
            inlinecss: [ minifyCss(), 'concat' ]
        }))
        .pipe(gulp.dest('dist/'));
});
```

**Comment by terinjokes** [comment]
Please see this [gulp recipe](https://github.com/gulpjs/gulp/blob/master/docs/recipes/combining-streams-to-handle-errors.md#combining-streams-to-handle-errors) (linked from the README) which will help you handle your stream's errors.

**Comment by chovy** [comment]
That yields the same error.

**Comment by terinjokes** [comment]
Which usemine implementation are you using. What is "rev"?

**Comment by chovy** [comment]
I'm using the first example on this README:

https://github.com/zont/gulp-usemin

**Comment by kxxoling** [comment]
Some error when trying gulp. My gulpfile.js is:

```js
var gulp = require('gulp');
var rev = require('gulp-rev-append');
var concat = require('gulp-concat');
var uglify = require('gulp-uglify');
var watch = require('gulp-watch')
var md5 = require("md5-file");
var replace = require('gulp-replace')

// Rerun the task when a file changes
gulp.task('scripts', function () {
  return gulp.src(['**/*.js'])
          .pipe(gulp.dest('dist'))
          .pipe(uglify())
          .pipe(gulp.dest('dist'));
});
```

**Comment by kxxoling** [comment]
I found the error is I ``node_modules/`` is also added under pattern ``**/*.js'``. It works after I changed this.
