### ISSUE TITLE
Can not parse: for (var x of y), version 1.4.1

### ISSUE THREAD

**Issue by Indomitable** [terinjokes/gulp-uglify#143]
at new JS_Parse_Error (~\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:196:18)
at js_error (~\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:204:11)
at croak (~\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:680:9)
at token_error (~\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:688:9)
at expect_token (~\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:701:9)
at expect (~\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:704:36)
at regular_for (~\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:934:9)
at for_ (~\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:930:16)
at ~\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:812:24
at ~\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:727:24

**Comment by terinjokes** [comment]
[UglifyJS2](https://github.com/mishoo/UglifyJS2) which this project uses to minify JavaScript does not yet support all of the new features of JavaScript (tracked at https://github.com/mishoo/UglifyJS2/issues/448).

You have two options:

1. Use you transform your JavaScript to the version that UglifyJS supports (ES5), via a tool like [babel](https://babeljs.io/).
2. Attempt to use the harmony branch of UglifyJS by following the examples from the above linked issue.
