### ISSUE TITLE
@charset "UTF-8"; throws error

### ISSUE THREAD

**Issue by aifrim** [terinjokes/gulp-uglify#153]
[14:47:52] { [Error: ~\app\assets\components\app.css: Unexpected character '@']
	  message: '~\\app\\assets\\components\\app.css: Unexpected character \'@\'',
	  fileName: '~\\app\\assets\\components\\app.css',
	  lineNumber: 3,
	  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (~\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:24:4), <anonymous>:1526:18)\n    at js_error (eval at <anonymous> (~\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:24:4), <anonymous>:1534:11)\n    at parse_error (eval at <anonymous> (~\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:24:4), <anonymous>:1647:9)\n    at next_token (eval at <anonymous> (~\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:24:4), <anonymous>:1911:9)\n    at eval (eval at <anonymous> (~\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:24:4), <anonymous>:1771:16)\n    at eval (eval at <anonymous> (~\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:24:4), <anonymous>:1869:24)\n    at handle_slash (eval at <anonymous> (~\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:24:4), <anonymous>:1845:20)\n    at Object.next_token [as input] (eval at <anonymous> (~\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:24:4), <anonymous>:1898:27)\n    at next (eval at <anonymous> (~\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:24:4), <anonymous>:2011:25)\n    at Object.parse (eval at <anonymous> (~\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:24:4), <anonymous>:1997:15)',
	  showStack: false,
	  showProperties: true,
	  plugin: 'gulp-uglify' }

This is [`app.css:3`](https://github.com/angular/bower-angular/blob/master/angular-csp.css) from bower-angular

	@charset "UTF-8";

**Comment by aifrim** [comment]
Your package only does JS. Sorry :+1:
