### ISSUE TITLE
Uglify not working with Foundation for Sites 6

### ISSUE THREAD

**Issue by dimoooooooon** [terinjokes/gulp-uglify#170]
I receive this error:

events.js:154
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/.../node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (/.../node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1534:11)
    at parse_error (eval at <anonymous> (/.../node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1647:9)
    at Object.next_token [as input] (eval at <anonymous> (/.../node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1912:9)
    at next (eval at <anonymous> (/.../node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2012:25)
    at subscripts (eval at <anonymous> (/.../node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2695:13)
    at subscripts (eval at <anonymous> (/.../node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2676:20)
    at subscripts (eval at <anonymous> (/.../node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2676:20)
    at expr_atom (eval at <anonymous> (/.../node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2552:20)
    at maybe_unary (eval at <anonymous> (/.../node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2716:19)

**Comment by terinjokes** [comment]
That's the default Node.js error handler for when you didn't handle errors from streams. If you attach an error handler, you'll get a `PluginError` that will tell you more information about the actual Parse error is.

See, for a basic example, [Combining streams to handle errors](https://github.com/gulpjs/gulp/blob/master/docs/recipes/combining-streams-to-handle-errors.md#combining-streams-to-handle-errors).
