### ISSUE TITLE
it can work on node v4.3.1 ?

### ISSUE THREAD

**Issue by zhishaofei3** [terinjokes/gulp-uglify#171]
it can work on node v4.3.1 ?

"D:\JetBrains\WebStorm 10.0.1\bin\runnerw.exe" d:\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js --color --gulpfile f:\gulp2\gulpfile.js mincss
[20:22:50] Using gulpfile f:\gulp2\gulpfile.js
[20:22:50] Starting 'mincss'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (f:\gulp2\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (f:\gulp2\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1534:11)
    at parse_error (eval at <anonymous> (f:\gulp2\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1647:9)
    at Object.next_token [as input] (eval at <anonymous> (f:\gulp2\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1912:9)
    at next (eval at <anonymous> (f:\gulp2\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2012:25)
    at Object.parse (eval at <anonymous> (f:\gulp2\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1998:15)
    at f:\gulp2\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:64:33
    at Array.forEach (native)
    at Object.exports.minify (f:\gulp2\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:59:15)
    at f:\gulp2\node_modules\gulp-uglify\minifier.js:65:22

**Comment by terinjokes** [comment]
That's the default Node.js error handler for when you didn't handle errors from streams. If you attach an error handler, you'll get a `PluginError` that will tell you more information about the actual Parse error is.

See, for a basic example, [Combining streams to handle errors](https://github.com/gulpjs/gulp/blob/master/docs/recipes/combining-streams-to-handle-errors.md#combining-streams-to-handle-errors).
