### ISSUE TITLE
 Unhandled 'error' event

### ISSUE THREAD

**Issue by WindWen** [terinjokes/gulp-uglify#172]
```js
Gulp.src(Path.join( Paths.source , "index.html"))
    .pipe(Useref({}, Lazypipe().pipe(Sourcemaps.init, { loadMaps: true })))
    .pipe(Gulpif('*.js', uglify()))
    .pipe(Babel(babelConfig))
    .pipe(Sourcemaps.write("."))
    .pipe(Gulpif('*.html', Version()))
    .pipe(Gulp.dest(Paths.dest))
```

```js
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (D:\Projects\frontend\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (D:\Projects\frontend\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1534:11)
    at croak (eval at <anonymous> (D:\Projects\frontend\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2026:9)

    at token_error (eval at <anonymous> (D:\Projects\frontend\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2034:9)
    at unexpected (eval at <anonymous> (D:\Projects\frontend\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2040:9)
    at expr_atom (eval at <anonymous> (D:\Projects\frontend\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2542:13)
    at maybe_unary (eval at <anonymous> (D:\Projects\frontend\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2716:19)
    at expr_ops (eval at <anonymous> (D:\Projects\frontend\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2751:24)
    at maybe_conditional (eval at <anonymous> (D:\Projects\frontend\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2756:20)
    at maybe_assign (eval at <anonymous> (D:\Projects\frontend\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2780:20)
```

**Comment by ozrevulsion** [comment]
I am also having this problem. I have found the offending code. It is in tools/nodejs. It is as follows:

`new Function("MOZ_SourceMap", "exports", FILES.map(function(file){
    return fs.readFileSync(file, "utf8");
}).join("\n\n"))(
    require("source-map"),
    UglifyJS
);`

I am yet to look at this any deeper as yet, at a short glance it's difficult for me to know what is going wrong here but I can have a look next time I get a chance. In the meantime maybe this will shed some light on the problem for someone smarter than me :)

**Comment by terinjokes** [comment]
That's the default Node.js error handler for when you didn't handle errors from streams. If you attach an error handler, you'll get a `PluginError` that will tell you more information about the actual Parse error is.

See, for a basic example, [Combining streams to handle errors](https://github.com/gulpjs/gulp/blob/master/docs/recipes/combining-streams-to-handle-errors.md#combining-streams-to-handle-errors).
