### ISSUE TITLE
JS Parse error

### ISSUE THREAD

**Issue by nmors** [terinjokes/gulp-uglify#173]
Will not uglify a strictified, browserified and reactified file:

happens with mangle on and off

Code:

``` JavaScript
// Copy all ui files
gulp.task('ui', ['clean', 'modules', 'ui-raw', 'ui-css'], function() {
  return gulp.src('ui/public/js/**/*.js')
    .pipe(uglify({mangle: true, warnings: true})) 
    .pipe(gulp.dest('build/ui/public/js'));
});
```

Output:

```
...
[16:56:34] Starting 'ui-raw'...
[16:56:34] Starting 'tmp'...
[16:56:35] Finished 'ui-raw' after 1 s
[16:56:35] Starting 'ui-css'...
[16:56:36] Finished 'ui-css' after 587 ms
[16:56:36] Starting 'ui'...
WARN: Non-strict equality against boolean: == true [0:33,962]
WARN: Non-strict equality against boolean: == true [0:33,1871]
WARN: Non-strict equality against boolean: == true [0:33,6044]
WARN: Non-strict equality against boolean: == true [0:33,6058]
WARN: Non-strict equality against boolean: == true [0:33,6697]
WARN: Non-strict equality against boolean: == true [0:33,6720]
WARN: Non-strict equality against boolean: == false [0:33,6827]
WARN: Non-strict equality against boolean: == true [0:33,6850]
WARN: Non-strict equality against boolean: == true [0:33,7021]

events.js:154
      throw er; // Unhandled 'error' event
      ^
Error
  at new JS_Parse_Error (<anonymous>:1526:18)
  at js_error (<anonymous>:1534:11)
  at croak (<anonymous>:2026:9)
  at token_error (<anonymous>:2034:9)
  at unexpected (<anonymous>:2040:9)
  at semicolon (<anonymous>:2060:56)
  at simple_statement (<anonymous>:2240:73)
  at eval (<anonymous>:2113:19)
  at eval (<anonymous>:2073:24)
  at block_ (<anonymous>:2353:20)
  at eval (<anonymous>:2326:25)
  at function_ (<anonymous>:2331:15)
  at expr_atom (<anonymous>:2546:24)
  at maybe_unary (<anonymous>:2716:19)
  at expr_ops (<anonymous>:2751:24)
  at maybe_conditional (<anonymous>:2756:20)
  at maybe_assign (<anonymous>:2780:20)
  at expression (<anonymous>:2799:20)
  at eval (<anonymous>:2615:25)
  at eval (<anonymous>:2073:24)
  at expr_atom (<anonymous>:2540:35)
  at maybe_unary (<anonymous>:2716:19)
  at expr_ops (<anonymous>:2751:24)
  at maybe_conditional (<anonymous>:2756:20)
  at maybe_assign (<anonymous>:2780:20)
  at expression (<anonymous>:2799:20)
  at expr_list (<anonymous>:2565:24)
  at subscripts (<anonymous>:2699:30)
  at subscripts (<anonymous>:2676:20)
  at expr_atom (<anonymous>:2552:20)
  at maybe_unary (<anonymous>:2716:19)
  at expr_ops (<anonymous>:2751:24)
  at maybe_conditional (<anonymous>:2756:20)
  at maybe_assign (<anonymous>:2780:20)
  at expression (<anonymous>:2799:20)
  at vardefs (<anonymous>:2433:56)
  at var_ (<anonymous>:2446:27)
  at eval (<anonymous>:2194:30)
  at eval (<anonymous>:2073:24)
  at block_ (<anonymous>:2353:20)
  at eval (<anonymous>:2326:25)
  at function_ (<anonymous>:2331:15)
  at expr_atom (<anonymous>:2546:24)
  at maybe_unary (<anonymous>:2716:19)
  at expr_ops (<anonymous>:2751:24)
  at maybe_conditional (<anonymous>:2756:20)
  at maybe_assign (<anonymous>:2780:20)
  at expression (<anonymous>:2799:20)
  at expr_list (<anonymous>:2565:24)
  at eval (<anonymous>:2575:23)
  at eval (<anonymous>:2073:24)
  at expr_atom (<anonymous>:2538:35)
  at maybe_unary (<anonymous>:2716:19)
  at expr_ops (<anonymous>:2751:24)
  at maybe_conditional (<anonymous>:2756:20)
  at maybe_assign (<anonymous>:2780:20)
  at expression (<anonymous>:2799:20)
  at eval (<anonymous>:2615:25)
  at eval (<anonymous>:2073:24)
  at expr_atom (<anonymous>:2540:35)
  at maybe_unary (<anonymous>:2716:19)
  at expr_ops (<anonymous>:2751:24)
  at maybe_conditional (<anonymous>:2756:20)
  at maybe_assign (<anonymous>:2780:20)
  at expression (<anonymous>:2799:20)
  at expr_list (<anonymous>:2565:24)
  at subscripts (<anonymous>:2699:30)
  at expr_atom (<anonymous>:2536:24)
  at maybe_unary (<anonymous>:2716:19)
  at expr_ops (<anonymous>:2751:24)
  at maybe_conditional (<anonymous>:2756:20)
  at maybe_assign (<anonymous>:2780:20)
  at expression (<anonymous>:2799:20)
  at simple_statement (<anonymous>:2240:55)
  at eval (<anonymous>:2125:24)
  at eval (<anonymous>:2073:24)
  at eval (<anonymous>:2827:23)
  at Object.parse (<anonymous>:2837:7)
  at /mydir/myapp/node_modules/uglify-js/tools/node.js:64:33
  at Array.forEach (native)
  at Object.exports.minify (/mydir/myapp/node_modules/uglify-js/tools/node.js:59:15)
  at /mydir/myapp/node_modules/gulp-uglify/minifier.js:65:22
  at trycatch (/mydir/myapp/node_modules/gulp-uglify/minifier.js:15:12)
  at DestroyableTransform.minify [as _transform] (/mydir/myapp/node_modules/gulp-uglify/minifier.js:64:19)
  at DestroyableTransform.Transform._read (/mydir/myapp/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
  at DestroyableTransform.Transform._write (/mydir/myapp/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
  at doWrite (/mydir/myapp/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:335:12)
  at writeOrBuffer (/mydir/myapp/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:321:5)
  at DestroyableTransform.Writable.write (/mydir/myapp/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:248:11)
  at write (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at emitNone (events.js:80:13)
  at DestroyableTransform.emit (events.js:179:7)
  at emitReadable_ (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at DestroyableTransform.noop [as _transform] (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/through2.js:26:3)
  at DestroyableTransform.Transform._read (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at emitNone (events.js:80:13)
  at DestroyableTransform.emit (events.js:179:7)
  at emitReadable_ (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at /mydir/myapp/node_modules/gulp/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:12:5
  at FSReqWrap.readFileAfterClose [as oncomplete] (evalmachine.<anonymous>:404:3)
```

**Comment by terinjokes** [comment]
@nmors Sorry that you're running into issues!

Have you checked out the [Errors](https://github.com/terinjokes/gulp-uglify#errors) section of the README? The error you're getting is from the default Node.js exception handler, which isn't very good in this case.

**Comment by mykone** [comment]
Hello, i am running into this error now. Is there a work-around for this "JS_Parse_Error" exception?

**Comment by mykone** [comment]
Actually, I was able to get the error using plumber. So I guess as @terinjokes said, it was an error handling issue.

**Comment by admonkey** [comment]
I'm getting the same error when trying to uglify [javascript classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes). Is this particular syntax not supported?

**Comment by terinjokes** [comment]
@admonkey The master branch of UglifyJS2 doesn't support them yet. Please see the last section in the gulp-uglify README for how you can use a different branch.

**Comment by terinjokes** [comment]
@mykone Please see the README section of "Errors" for more information on how to proceed.

**Comment by admonkey** [comment]
@terinjokes thanks, but it doesn't appear that any of the other branches support ECMA6 either - am I missing something?

**Comment by terinjokes** [comment]
@admonkey the "harmony" branch of [UglifyJS2](https://github.com/mishoo/UglifyJS2) does. See also [`uglify-js-harmony`](https://npm.im/uglify-js-harmony).

**Comment by nmors** [comment]
even when compiling to ES5 i'm still getting issues. There are no errors in my code, its been linted fine

**Comment by terinjokes** [comment]
@nmors I've explained how to get the error message from UglifyJS. If you're having issue with how it parses or minfies, please open an issue with the [UglifyJS2](https://github.com/mishoo/UglifyJS2) project.
