### ISSUE TITLE
TypeError: file.isNull is not a function

### ISSUE THREAD

**Issue by mnzt** [terinjokes/gulp-uglify#183]
Node version: v6.0.0
NPM version: 3.8.6
gulp-uglify version: 1.5.3

Full track trace error:
```
/home/mnzt/vessel/projects/coffer/node_modules/gulp-uglify/minifier.js:50
    if (file.isNull()) {
             ^

TypeError: file.isNull is not a function
    at DestroyableTransform.minify [as _transform] (/home/mnzt/vessel/projects/coffer/node_modules/gulp-uglify/minifier.js:50:14)
    at DestroyableTransform.Transform._read (/home/mnzt/vessel/projects/coffer/node_modules/gulp-uglify/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/mnzt/vessel/projects/coffer/node_modules/gulp-uglify/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/mnzt/vessel/projects/coffer/node_modules/gulp-uglify/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/home/mnzt/vessel/projects/coffer/node_modules/gulp-uglify/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/home/mnzt/vessel/projects/coffer/node_modules/gulp-uglify/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at Readable.ondata (/home/mnzt/vessel/projects/coffer/node_modules/read-only-stream/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at emitOne (events.js:96:13)
    at Readable.emit (events.js:188:7)
    at readableAddChunk (/home/mnzt/vessel/projects/coffer/node_modules/read-only-stream/node_modules/readable-stream/lib/_stream_readable.js:198:18)

```

**Comment by terinjokes** [comment]
Please include a snippet from your gulpfile.

**Comment by mnzt** [comment]
```
gulp.task('react', function () {
  browserify({
    entries: __dirname + '/src/app/src/index.jsx',
    extensions: ['.jsx'],
    debug: true
  })
  .transform(babelify, {presets: ["es2015", "react"]})
  .bundle()
  .pipe(uglify())
  .pipe(source('bundle.js'))
  .pipe(gulp.dest(__dirname + '/dist/coffer/js'));
});

```
With relevant imports, etc.

**Comment by terinjokes** [comment]
gulp-uglify only works with Vinyl-backed streams. Browserify's bundle method returns a stream of data.

You can use [vinyl-source-stream](https://www.npmjs.com/package/vinyl-source-stream) to convert very easily.

**Comment by mnzt** [comment]
Ah my mistake - thank you

**Comment by lukaszkups** [comment]
@terinjokes @tobbbles sorry for digging out so old issue, but I've got the same error right now - how the task chain should look like with `vinyl-source-stream` package? I've tried various combinations but still receive that error :|
