### ISSUE TITLE
JS_Parse_Error

### ISSUE THREAD

**Issue by zakiaziz** [terinjokes/gulp-uglify#184]
I have a `public/app.js` file that I want minified. I have a gulp task defined like this:
```
var uglify  = require('gulp-uglify');

gulp.task('uglify-app-js', function() {
  return gulp.src('public/app.js')
    .pipe(uglify())
    .pipe(gulp.dest('public/'));
});
```
Running it outputs an error:
```
$ gulp uglify-app-js
[20:41:06] Using gulpfile ~/project/gulpfile.js
[20:41:06] Starting 'uglify-app-js'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/home/user/project/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:1525:18)
    at js_error (eval at <anonymous> (/home/user/project/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:1533:11)
    at croak (eval at <anonymous> (/home/user/project/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2025:9)
    at token_error (eval at <anonymous> (/home/user/project/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2033:9)
    at unexpected (eval at <anonymous> (/home/user/project/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2039:9)
    at expr_atom (eval at <anonymous> (/home/user/project/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2541:13)
    at maybe_unary (eval at <anonymous> (/home/user/project/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2715:19)
    at expr_ops (eval at <anonymous> (/home/user/project/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2750:24)
    at maybe_conditional (eval at <anonymous> (/home/user/project/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2755:20)
    at maybe_assign (eval at <anonymous> (/home/user/project/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2779:20)
    at expression (eval at <anonymous> (/home/user/project/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2798:20)
    at expr_atom (eval at <anonymous> (/home/user/project/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2531:26)
    at maybe_unary (eval at <anonymous> (/home/user/project/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2715:19)
```
I'm pretty new to gulp (and JS in general) and am not sure how to go about debugging this issue.

**Comment by terinjokes** [comment]
@zakiaziz In short, by default Node.js streams don't propagate errors in the expected way. Please see this project's [README](https://github.com/terinjokes/gulp-uglify#usage) (and linked article) for the recommended way to handle errors.
