### ISSUE TITLE
Unexpected character '`'

### ISSUE THREAD

**Issue by mrasoahaingo** [terinjokes/gulp-uglify#199]
Hello devs,

I'm facing an issue when I try to uglify a part of my javascript code that includes some [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

This is the part that causes the error:

```
  //...
  Promise.reject(`${tagId} is not defined`);
  //...
```

This is the full stack error:

```
Error\n    at new JS_Parse_Error (eval at <anonymous> (/home/docker/public_html/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)\n    at js_error (eval at <anonymous> (/home/docker/public_html/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)\n    at parse_error (eval at <anonymous> (/home/docker/public_html/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1667:9)\n    at Object.next_token [as input] (eval at <anonymous> (/home/docker/public_html/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1946:9)\n    at next (eval at <anonymous> (/home/docker/public_html/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2075:25)\n    at subscripts (eval at <anonymous> (/home/docker/public_html/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2771:13)\n    at subscripts (eval at <anonymous> (/home/docker/public_html/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2752:20)\n    at expr_atom (eval at <anonymous> (/home/docker/public_html/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2628:20)\n    at maybe_unary (eval at <anonymous> (/home/docker/public_html/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)\n    at expr_op (eval at <anonymous> (/home/docker/public_html/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2814:33)\n    at expr_ops (eval at <anonymous> (/home/docker/public_html/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:16)\n    at maybe_conditional (eval at <anonymous> (/home/docker/public_html/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:20)\n    at maybe_assign (eval at <anonymous> (/home/docker/public_html/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2856:20)\n    at expression (eval at <anonymous> (/home/docker/public_html/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2875:20)\n    at eval (eval at <anonymous> (/home/docker/public_html/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2245:39)\n    at eval (eval at <anonymous> (/home/docker/public_html/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
```

Did I miss some settings or it doesn't support template literals? :(

Thank you for your help.

**Comment by terinjokes** [comment]
UglifyJS2, the thing that actually does the minification, is still working on completing ES6 support. You can follow the instructions in the README here to give the harmony branch a try, or first transpire to ES5 using Babel.
