### ISSUE TITLE
lodash module terminating both gulp and app to execute

### ISSUE THREAD

**Issue by DJviolin** [terinjokes/gulp-uglify#204]
```shell
C:\www\node\lantosistvan\app\node_modules\lodash\lodash.js:1281
    context = context ? _.defaults({}, context, _.pick(root, contextProps)) : root;
                          ^

TypeError: Cannot read property 'prototype' of undefined
    at runInContext (C:\www\node\lantosistvan\app\node_modules\lodash\lodash.js:1281:27)
    at Object.<anonymous> (C:\www\node\lantosistvan\app\node_modules\lodash\lodash.js:16580:11)
    at Object.<anonymous> (C:\www\node\lantosistvan\app\node_modules\lodash\lodash.js:16607:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

`lodash` is only installed for `gulp-uglify`:

```shell
$ npm ls lodash
lantosistvan-portfolio@1.0.0 C:\www\node\lantosistvan\app
`-- gulp-uglify@2.0.0
  `-- lodash@4.14.1
```

**Comment by DJviolin** [comment]
The issue is caused by `lodash` when you executing your app with `--ignition` V8 flag.

**Comment by terinjokes** [comment]
@djviolin please post how you're calling gulp-ugljfy from your gulpfile.

**Comment by DJviolin** [comment]
Sorry, meanwhile I closed this issue because this is clearly `lodash` issue, not `gulp-uglify`.

**Comment by DJviolin** [comment]
For the record, this is how I call `gulp-uglify`:

```js
const gulp = require('gulp'),
      uglify   = require('gulp-uglify');

gulp.task('uglify', () =>
  gulp.src(paths.uglify)
    .pipe(uglify({ output: {quote_style: 1} }))
    .pipe(rename({ extname: '.min.js' }))
    .pipe(gulp.dest('public/javascripts'))
);
```

**Comment by terinjokes** [comment]
Can you find or create a lodash ticket and link it here? Thanks!

**Comment by DJviolin** [comment]
I already created there: https://github.com/lodash/lodash/issues/2563

Author suggested better to send a ticket for V8 issue channel, because the possible error is in the `Ignition` compiler: https://bugs.chromium.org/p/v8/issues/list

Not a problem to send Node.js issues to them?
