### ISSUE TITLE
gulp-uglify unable to minify javascript

### ISSUE THREAD

**Issue by wangshan** [terinjokes/gulp-uglify#240]
I have the following error when using gulp-uglify 2.0.0 with ES6, node 7.0.0 and gulp 3.9.1:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (/Developer/sandbox/projects/footnote/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at wrapper (/Developer/sandbox/projects/footnote/node_modules/lodash/_createHybridWrapper.js:88:15)
    at trycatch (/Developer/sandbox/projects/footnote/node_modules/gulp-uglify/minifier.js:26:12)
    at DestroyableTransform.minify [as _transform] (/Developer/sandbox/projects/footnote/node_modules/gulp-uglify/minifier.js:76:19)
    at DestroyableTransform.Transform._read (/Developer/sandbox/projects/footnote/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Developer/sandbox/projects/footnote/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Developer/sandbox/projects/footnote/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Developer/sandbox/projects/footnote/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Developer/sandbox/projects/footnote/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at write (/Developer/sandbox/projects/footnote/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:623:24)
```

I use typescript to generate es6 target, is this an es6 problem?

**Comment by terinjokes** [comment]
@wangshan Please see [Why Use Pump?](https://github.com/terinjokes/gulp-uglify/blob/master/docs/why-use-pump/README.md#why-use-pump) for how to get better errors.

Yes, UglifyJS2 doesn't support ES6. Please convert to ES5 first.
