### ISSUE TITLE
unable to minify JavaScript

### ISSUE THREAD

**Issue by barbalex** [terinjokes/gulp-uglify#243]
Suddenly in [one of my projects](https://github.com/FNSKtZH/apflora) building does not work any more.

I could brake it down to this:

    PS C:\Users\alex\apflora> gulp prod_build_src
    (node:1144) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
    [15:28:13] Using gulpfile ~\apflora\gulpfile.js
    [15:28:13] Starting 'prod_build_src'...

    events.js:160
          throw er; // Unhandled 'error' event
          ^
    GulpUglifyError: unable to minify JavaScript
        at createError (C:\Users\alex\apflora\node_modules\gulp-uglify\lib\create-error.js:6:14)
        at wrapper (C:\Users\alex\apflora\node_modules\gulp-uglify\node_modules\lodash\_createHybrid.js:87:15)
        at trycatch (C:\Users\alex\apflora\node_modules\gulp-uglify\minifier.js:26:12)
        at DestroyableTransform.minify [as _transform] (C:\Users\alex\apflora\node_modules\gulp-uglify\minifier.js:76:19)
        at DestroyableTransform.Transform._read (C:\Users\alex\apflora\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:10)
        at DestroyableTransform.Transform._write (C:\Users\alex\apflora\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:160:12)
        at doWrite (C:\Users\alex\apflora\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:335:12)
        at writeOrBuffer (C:\Users\alex\apflora\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:321:5)
        at DestroyableTransform.Writable.write (C:\Users\alex\apflora\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:248:11)
        at write (C:\Users\alex\apflora\node_modules\gulp-concat\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    PS C:\Users\alex\apflora>

gulp-uglify is used in this file: https://github.com/FNSKtZH/apflora/blob/master/gulp-tasks/prod_build_src.js

I did see this other issue: https://github.com/terinjokes/gulp-uglify/issues/240 where you mention es6 being a problem. But as far as I can see I am not using it here.

What could be wrong?

**Comment by terinjokes** [comment]
@barbalex If you capture the error, rather than letting it bubble all the way up and crash the program, you can capture the error and view the properties, [documented in the README](https://github.com/terinjokes/gulp-uglify#errors).

That should tell you more about the error. See [Why Use Pump?](https://github.com/terinjokes/gulp-uglify/tree/master/docs/why-use-pump) for an easy way to capture these errors.

**Comment by barbalex** [comment]
well, I did have a look at that - but to be honest: I could not figure out how to apply it in my case:

    var gulp = require('gulp')
    var uglify = require('gulp-uglify')
    var concat = require('gulp-concat')

    gulp.task('prod_build_src', function () {
      return gulp.src([
        'src/jquery-ui.js',
        'src/jquery.ui.touch-punch.js',
        'src/jquery.cookie.js',
        'src/jquery.hotkeys.js',
        'src/hammer.js',
        'src/jquery.hammer.js',
        'src/markerclusterer.js',
        'src/markerwithlabel.js',
        'src/ruler.js',
        'src/jsuri.js',
        'src/jquery.qtip.js',
        'src/jquery.fileDownload.js',
        'src/xlsx.js',
        'src/FileSaver.js',
        'src/canvas-toBlob.js',
        'src/apflora_browserified.js',
        'src/underscore.js',
        'src/handlebars.js',
        'src/list.js'
      ])
        .pipe(concat('apflora_built.js'))
        .pipe(uglify())
        .pipe(gulp.dest('./src'))
        .pipe(gulp.dest('./dist/src'))
    })

**Comment by terinjokes** [comment]
Remove all the `pipe`s, add "cb" as the parameter to the task, then pass an array of all the work (the stuff previously joined by `pipe`) and the callback to `pump`.

```javascript
var gulp = require('gulp')
var uglify = require('gulp-uglify')
var concat = require('gulp-concat')
var pump = require('pump')

gulp.task('prod_build_src', function (cb) {
  pump([
      gulp.src([
         'src/jquery-ui.js',
         'src/jquery.ui.touch-punch.js',
         'src/jquery.cookie.js',
         'src/jquery.hotkeys.js',
         'src/hammer.js',
         'src/jquery.hammer.js',
         'src/markerclusterer.js',
         'src/markerwithlabel.js',
         'src/ruler.js',
         'src/jsuri.js',
         'src/jquery.qtip.js',
         'src/jquery.fileDownload.js',
         'src/xlsx.js',
         'src/FileSaver.js',
         'src/canvas-toBlob.js',
         'src/apflora_browserified.js',
         'src/underscore.js',
         'src/handlebars.js',
         'src/list.js'
      ]),
      concat('apflora_built.js'),
      uglify(),
      gulp.dest('./src'),
      gulp.dest('./dist/src')
  ], cb)
})
```

**Comment by barbalex** [comment]
Thanks a lot and SORRY for bothering you because after answering I had another look and actually managed it myself.

You are right, using pump is revealing. I now get: `Task 'prod_built_src' is not in your gulpfile`.

Which seems to point at a different problem. But no idea what as `prod_build_src.js` is definitely in the `gulp-tasks` folder and my gulpfile is like this:

    /*

     Quelle: https://github.com/greypants/gulp-starter

     gulpfile.js
     ===========
     Rather than manage one giant configuration file responsible
     for creating multiple tasks, each task has been broken out into
     its own file in gulp/tasks. Any files in that directory get
     automatically required below.

     To add a new task, simply add a new task file that directory.
     gulp/tasks/default.js specifies the default set of tasks to run
     when you run `gulp`.
     */

    var requireDir = require('require-dir')

    // initiate modularized tasks
    requireDir('./gulp-tasks', { recurse: true })

Well, I guess I will have to dive back into gulp (haven't used it in the more recent projects) and find a different way to build gulpfiles.

**Comment by barbalex** [comment]
I deleted `prod_build_src.js` and recreated it. Now I don't get `Task 'prod_built_src' is not in your gulpfile` any more.

Instead this here:

    [17:35:38] GulpUglifyError: unable to minify JavaScript
    Caused by: SyntaxError: Unexpected character '`' (line: 63520, col: 12, pos: 3372706)

    Error
        at new JS_Parse_Error (eval at <anonymous> (C:\Users\alex\apflora\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1545:18)
        at js_error (eval at <anonymous> (C:\Users\alex\apflora\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1553:11)
        at parse_error (eval at <anonymous> (C:\Users\alex\apflora\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1677:9)
        at Object.next_token [as input] (eval at <anonymous> (C:\Users\alex\apflora\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1946:9)
        at next (eval at <anonymous> (C:\Users\alex\apflora\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2075:25)
        at subscripts (eval at <anonymous> (C:\Users\alex\apflora\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2771:13)
        at expr_atom (eval at <anonymous> (C:\Users\alex\apflora\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2628:20)
        at maybe_unary (eval at <anonymous> (C:\Users\alex\apflora\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2792:19)
        at expr_ops (eval at <anonymous> (C:\Users\alex\apflora\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2827:24)
        at maybe_conditional (eval at <anonymous> (C:\Users\alex\apflora\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2832:20)
        at maybe_assign (eval at <anonymous> (C:\Users\alex\apflora\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2856:20)
        at expression (eval at <anonymous> (C:\Users\alex\apflora\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2875:20)
        at simple_statement (eval at <anonymous> (C:\Users\alex\apflora\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2314:55)
    PS C:\Users\alex\apflora>

If I uncoment the `uglify()`-call, the error does not occur.

Is it possible that uglify does not work if any of the imported dependencies contain es6?

Though I have not updated these dependencies in quite a while.

**Comment by barbalex** [comment]
o.k., haven't worked with this build in ages: the actual project code is included and I have startet using es6 because all the targeted browsers can deal with it.

So that is where the '`' comes from.

But how can I uglify my project code using gulp when it contains es6?

**Comment by terinjokes** [comment]
You need to either transform to ES5—since UglifyJS hasn't updated for full support yet—or switch to a minifier that supports ES6.

**Comment by barbalex** [comment]
thanks

**Comment by chunhsiao** [comment]
I met same problem and resolved it. The following code is the solution.

```javascript
browserify({
            entries: scriptPath.src,
            debug: true
        })
        .transform('babelify', {presets: ['es2015']})
        .bundle()
        .pipe(source('bundle.js'))
        .pipe(buffer())
        .pipe(uglify())
        .pipe(gulp.dest(scriptPath.dist));
```
The finally that  I resolved it is to create the following code
 ```javascript 
transform('babelify', {presets: ['es2015']})
```

**Comment by hamzaouiii** [comment]
I had the same issue and reason was using ES6.. converted it back to ES5 and it was fine

**Comment by mrpsweet** [comment]
I had the same issue . Actually is ES6 dada~~

**Comment by ftp82** [comment]
Can any of you guys tell me how to revert to ES5?

**Comment by hamzaouiii** [comment]
use something like https://babeljs.io/

**Comment by 786lokesh** [comment]
@terinjokes I don't know how sometimes I also ran into this problem. I think it crashed because sometimes I kill the running gulp program and restart the gulp command interrupting the watchers on gulp. 

```
gulp.task('watch', function() {
  	gulp.watch(paths.scripts, ['scripts']);
  	gulp.watch(paths.images, ['images']);
  	gulp.watch(paths.sass, ['sass']);
});
```
Once I restart the system it works absolutely fine without throwing this error. But restarting is becoming a painful process now. 
Any suggestion for fixing this issue ?
