### ISSUE TITLE
 GulpUglifyError: unable to minify JavaScript

### ISSUE THREAD

**Issue by erwin009** [terinjokes/gulp-uglify#249]
events.js:141
      throw er; // Unhandled 'error' event
      ^
 GulpUglifyError: unable to minify JavaScript
    at createError (E:\nodejs\node-express-test\node_modules\gulp-uglify\lib\create-error.js:6:14)
    at wrapper (E:\nodejs\node-express-test\node_modules\gulp-uglify\node_modules\lodash\_createHybrid.js:87:15)
    at trycatch (E:\nodejs\node-express-test\node_modules\gulp-uglify\minifier.js:26:12)
    at DestroyableTransform.minify [as _transform] (E:\nodejs\node-express-test\node_modules\gulp-uglify\minifier.js:76:19)
    at DestroyableTransform.Transform._read (E:\nodejs\node-express-test\node_modules\gulp-uglify\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (E:\nodejs\node-express-test\node_modules\gulp-uglify\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (E:\nodejs\node-express-test\node_modules\gulp-uglify\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:313:64)
    at writeOrBuffer (E:\nodejs\node-express-test\node_modules\gulp-uglify\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (E:\nodejs\node-express-test\node_modules\gulp-uglify\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:241:11)
    at Transform.ondata (_stream_readable.js:542:20)

**Comment by enricoaleandri** [comment]
Use this syntax to handle the error and let the code go hover : 

var gutil = require('gulp-util');

  $.uglify().on('error', function(err) {
    gutil.log(gutil.colors.red('[Error]'), err.toString());
    this.emit('end');
  })

You will see the error printed in the console.

**Comment by erwin009** [comment]
thanks @enricoaleandri

**Comment by terinjokes** [comment]
@erwin009 It's recommend that you use something similar to the following:

```javascript
var gulp = require('gulp');
var uglify = require('gulp-uglify');
var pump = require('pump');

gulp.task('compress', function (cb) {
  pump([
        gulp.src('lib/*.js'),
        uglify(),
        gulp.dest('dist')
    ],
    cb
  );
});
```

This way the error can be propagated to (and displayed by) Gulp.

**Comment by fangdora** [comment]
thanks @terinjokes

**Comment by nathanhornby** [comment]
Thanks both, I combined your answers!

```javascript
gutil = require('gulp-util')

gulp.task('scripts', function() {
  return gulp.src(['dev_assets/scripts/*.js'])
    .pipe(concat('all.min.js'))
    .pipe(uglify())
    .on('error', function (err) { gutil.log(gutil.colors.red('[Error]'), err.toString()); })
    .pipe(gulp.dest('public/js'))
    .pipe(livereload());
})
```

**Comment by eriku** [comment]
I know this is closed but I thought I'd add in my fix (using plumber). The trick for me was to get plumber to throw the error **BEFORE** trying to uglify the script instead of after.

```
gulp.task('scripts', function() {
		return gulp.src(jsSource)
				.pipe(concat('application.js'))
				.pipe(gulp.dest(jsDest))
				.pipe(plumber({
					errorHandler: notify.onError({
						title: 'Gulp',
						message: '<%= error.message %>',
					})
				}))
				.pipe(uglify())
				.pipe(gulp.dest(jsDest))
				.pipe(notify({
						title: 'Gulp',
						message: 'Scripts Done'
				}));
	});
```

**Comment by BESAFX** [comment]
Thanks @nathanhornby 
Your Answer Rescue me

**Comment by zhaiduo** [comment]
I think it's better to interrupt the error in pipe.

**Comment by zwtokio** [comment]
Mi error fue, querer minificar "ecmascript 6" const and let.

**Comment by revolter** [comment]
@enricoaleandri, What is `$`?

**Comment by forrestab** [comment]
@revolter I am assuming you are talking about the `$` in @enricoaleandri's comment, he is probably using the [gulp-load-plugins](https://www.npmjs.com/package/gulp-load-plugins) package. I typically see the pattern `const $ = require("gulp-load-plugins")();` when loading this package to use other installed packages without explicitly requiring them.

**Comment by revolter** [comment]
@forrestab, Thank you.

**Comment by yangfan0095** [comment]
i  had solved  the problem  according to the  above way 
`
const  gutil = require('gulp-util');
const $ = require("gulp-load-plugins")();

$.uglify().on('error', function (err) {
    gutil.log(gutil.colors.red('[Error]'), err.toString());
    this.emit('end');
})
`
when i execute the gulp task again and the logs had help me show the error
`
Finished 'enterprisemobilejs' after 1.06 s
[18:29:13] Starting 'enterprisemobilehtml'...
[18:29:13] Finished 'minifycss' after 1.13 s
[18:29:13] [Error] GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: name (locations)
File: /Users/fanyang/D/qiyuesuo/web-expose/public/js/sign/event.js
Line: 70

events.js:183
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (/Users/fanyang/D/qiyuesuo/web-expose/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at wrapper (/Users/fanyang/D/qiyuesuo/web-expose/node_modules/lodash/_createHybrid.js:87:15)
    at trycatch (/Users/fanyang/D/qiyuesuo/web-expose/node_modules/gulp-uglify/minifier.js:26:12)
    at Destroyable

`

**Comment by AnshulNautiyal** [comment]
I got this error because I am declaring a variable using 'let' in the for loop. Then i replaced the 'let' with 'var' and run the gulp task, it works fine.

**Comment by fusion35** [comment]
I was using let and const. My fix was to replace gulp-uglify with gulp-uglify-es.

**Comment by eslam15** [comment]
> Use this syntax to handle the error and let the code go hover :
> 
> var gutil = require('gulp-util');
> 
> $.uglify().on('error', function(err) {
> gutil.log(gutil.colors.red('[Error]'), err.toString());
> this.emit('end');
> })
> 
> You will see the error printed in the console.

Realy thanks :) @enricoaleandri

**Comment by chenkuangAmber** [comment]
I also have the same error, the compiler recommended using ‘let’, after the compilation will fail, in the case of ‘var’ you can compile normally, thank you

**Comment by bogdan-dubyk** [comment]
I know it's clodes, but I have error like 

```
GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: punc «.»
File: app/scripts/vendor.js
Line: 22338
Col: 142
```
but in app directory I do not have vendor.js script at all.....

**Comment by Ksantacr** [comment]
Show error information didn't help 

`[18:44:28] Starting 'min'...
[18:44:28] Starting 'min:js'...
[18:44:28] Finished 'min:js' after 7 ms
[18:44:28] Starting 'min:css'...
[18:44:28] Finished 'min:css' after 1.65 ms
[18:44:28] Finished 'min' after 11 ms
[18:44:28] [Error] GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: operator «=», expected: punc «,»
File: wwwroot\js\site.min.js
Line: 15
Col: 29`
