### ISSUE TITLE
Error using with uglify-js-harmony

### ISSUE THREAD

**Issue by opus1269** [terinjokes/gulp-uglify#266]
I am getting the attached error when using the minify endpoint with uglify-js-harmony. Any idea what the issue is?

The local uglifyjs runs fine from the command line.  I deleted the global version and cleared the npm cache as well. Using latest versions of everything.
If I install and replace  uglify-js-harmony with  uglify-js it also works (chokes on  the let, but works fine with es5).

My gulpfile is set up like this:

```
...
const uglifyjs = require('uglify-js-harmony');
const minifier = require('gulp-uglify/minifier');
gulp.task('scriptstest', function() {
	return gulp.src('user.js')
		.pipe(minifier({}, uglifyjs).on('error', gutil.log))
		.pipe(gulp.dest('user.min.js'));
});
```

user.js is:

```
/*
 *
 * strip comment
 */
let i = 0;
```

```
$ gulp scriptstest
[16:40:07] Using gulpfile ~\Documents\GitHub\Clip-Man-Chrome\gulpfile.js
[16:40:07] Starting 'scriptstest'...
[16:40:07] { GulpUglifyError: unable to minify JavaScript
    at createError (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\gulp-uglify\lib\create-error.js:6:14)
    at wrapper (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\lodash\_createHybrid.js:87:15)
    at trycatch (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\gulp-uglify\minifier.js:26:12)
    at DestroyableTransform.minify [as _transform] (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\gulp-uglify\minifier.js:76:19)
    at DestroyableTransform.Transform._read (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\readable-stream\lib\_stream_writable.js:347:64)
    at writeOrBuffer (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\readable-stream\lib\_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\readable-stream\lib\_stream_writable.js:274:11)
    at write (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24)
  cause:
   TypeError: files.forEach is not a function
       at Object.exports.minify (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\uglify-js-harmony\tools\node.js:56:15)
       at C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\gulp-uglify\minifier.js:79:22
       at trycatch (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\gulp-uglify\minifier.js:24:12)
       at DestroyableTransform.minify [as _transform] (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\gulp-uglify\minifier.js:76:19)
       at DestroyableTransform.Transform._read (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\readable-stream\lib\_stream_transform.js:159:10)
       at DestroyableTransform.Transform._write (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\readable-stream\lib\_stream_transform.js:147:83)
       at doWrite (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\readable-stream\lib\_stream_writable.js:347:64)
       at writeOrBuffer (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\readable-stream\lib\_stream_writable.js:336:5)
       at DestroyableTransform.Writable.write (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\readable-stream\lib\_stream_writable.js:274:11)
       at write (C:\Users\mike\Documents\GitHub\Clip-Man-Chrome\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24),
  plugin: 'gulp-uglify',
  fileName: 'C:\\Users\\mike\\Documents\\GitHub\\Clip-Man-Chrome\\user.js',
  showStack: false }

```

**Comment by opus1269** [comment]
My bad - had old version of harmony after all
