### ISSUE TITLE
Why unable to minify JavaScript?

### ISSUE THREAD

**Issue by binarykitchen** [terinjokes/gulp-uglify#281]
Happens in my gulp task every time. There is an unhandled error event and it doesn't say what part exactly is not minify-able? Using version 2.1.2 here

```
events.js:163
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (/home/michael-heuberger/code/videomail-client/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at wrapper (/home/michael-heuberger/code/videomail-client/node_modules/lodash/_createHybrid.js:87:15)
    at trycatch (/home/michael-heuberger/code/videomail-client/node_modules/gulp-uglify/minifier.js:26:12)
    at DestroyableTransform.minify [as _transform] (/home/michael-heuberger/code/videomail-client/node_modules/gulp-uglify/minifier.js:79:19)
    at DestroyableTransform.Transform._read (/home/michael-heuberger/code/videomail-client/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/michael-heuberger/code/videomail-client/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/michael-heuberger/code/videomail-client/node_modules/readable-stream/lib/_stream_writable.js:345:64)
    at writeOrBuffer (/home/michael-heuberger/code/videomail-client/node_modules/readable-stream/lib/_stream_writable.js:334:5)
    at DestroyableTransform.Writable.write (/home/michael-heuberger/code/videomail-client/node_modules/readable-stream/lib/_stream_writable.js:271:11)
    at Transform.ondata (_stream_readable.js:555:20)
error Command failed with exit code 1.
```

**Comment by binarykitchen** [comment]
that's the gulp task where i am using uglify ...

```js
gulp.task('browserify', ['clean:js'], function (cb) {
  const entry = path.join(__dirname, '/src/index.js')
  const bundler = browserify({
    entries: [entry],
    basedir: __dirname,
    globals: false,
    debug: true // enables source maps
  })

  bundler
    .require(entry, {expose: 'videomail-client'})
    .bundle()
    .on('error', function (err) {
      plugins.util.log(plugins.util.colors.red('[Error]'), err.toString())
    })
    .on('log', plugins.util.log)
    .on('end', cb)
    .pipe(source('./src/')) // gives streaming vinyl file object
    .pipe(buffer()) // required because the next steps do not support streams
    .pipe(plugins.concat('videomail-client.js'))
    .pipe(gulp.dest('dist'))
    .pipe(plugins.if(options.minify, plugins.rename({suffix: '.min'})))
    .pipe(plugins.if(options.minify, plugins.uglify()))
    .pipe(plugins.if(options.minify, gulp.dest('dist')))
    .pipe(plugins.connect.reload())
})
```

**Comment by binarykitchen** [comment]
anyone?

**Comment by yangjunjun** [comment]
you may have syntax error or  used ES6 syntax. you can try https://skalman.github.io/UglifyJS-online/ firstly.

**Comment by terinjokes** [comment]
@binarykitchen If you use `pump` instead of chaining with `.pipe` you'll probably will get the full error message.

**Comment by binarykitchen** [comment]
ah yeah, pump did it - thx guys
