### ISSUE TITLE
Error with upgrading to v3

### ISSUE THREAD

**Issue by falsandtru** [terinjokes/gulp-uglify#295]
2.1.2 works fine, but 3.0.0 does not.

```
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (/home/travis/build/falsandtru/spica/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at apply (/home/travis/build/falsandtru/spica/node_modules/lodash/_apply.js:16:25)
    at wrapper (/home/travis/build/falsandtru/spica/node_modules/lodash/_createCurry.js:41:12)
    at /home/travis/build/falsandtru/spica/node_modules/gulp-uglify/lib/minify.js:54:15
    at DestroyableTransform._transform (/home/travis/build/falsandtru/spica/node_modules/gulp-uglify/composer.js:10:23)
    at DestroyableTransform.Transform._read (/home/travis/build/falsandtru/spica/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/travis/build/falsandtru/spica/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/travis/build/falsandtru/spica/node_modules/readable-stream/lib/_stream_writable.js:338:64)
    at writeOrBuffer (/home/travis/build/falsandtru/spica/node_modules/readable-stream/lib/_stream_writable.js:327:5)
    at DestroyableTransform.Writable.write (/home/travis/build/falsandtru/spica/node_modules/readable-stream/lib/_stream_writable.js:264:11)
    at DestroyableTransform.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:191:7)
    at DestroyableTransform.<anonymous> (/home/travis/build/falsandtru/spica/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:786:14)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:188:7)
```

https://travis-ci.org/falsandtru/spica/jobs/235995926#L1480

**Comment by terinjokes** [comment]
You should consider using the `pump` module, as explained in the README, as you'll get better errors, not just for gulp-uglify, but for your entire build pipeline.

In this case, the error message would have explained that the `preserveComments` option is no longer valid. The release notes for gulp-uglify v3.0.0 explains how to migrate.

**Comment by falsandtru** [comment]
Succeeded with the following code, thanks.

```js
gulp.task('ts:dist', function (done) {
  pump([
    compile(config.ts.dist.src)
      .pipe($.unassert())
      .pipe($.header(config.banner))
      .pipe(gulp.dest(config.ts.dist.dest))
      .pipe($.rename({ extname: '.min.js' })),
    $.uglify({ output: { comments: 'all' } }),
    gulp.dest(config.ts.dist.dest)
  ], done);
});
```

**Comment by terinjokes** [comment]
@falsandtru you really should remove the `.pipe` calls and simply list them all out as individual array members. That way you get the benefits of using `pump` for all the parts.

**Comment by falsandtru** [comment]
Okay, I changed it as follows.

```js
gulp.task('ts:dist', function (done) {
  pump([
    compile(config.ts.dist.src),
    $.unassert(),
    $.header(config.banner),
    gulp.dest(config.ts.dist.dest),
    $.rename({ extname: '.min.js' }),
    $.uglify({ output: { comments: 'all' } }),
    gulp.dest(config.ts.dist.dest)
  ], done);
});
```

**Comment by terinjokes** [comment]
:+1:
