### ISSUE TITLE
Strange error if I add file with same syntax content as previous one

### ISSUE THREAD

**Issue by bravesomesh** [terinjokes/gulp-uglify#296]
`/home/yolo/yolo_rpi_server/mock/server/utils.js added to sources 

undefined:1786
    throw new JS_Parse_Error(message, filename, line, col, pos);
    ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:1778:18)
    at js_error (eval at <anonymous> (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:1786:11)
    at croak (eval at <anonymous> (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:2299:9)
    at token_error (eval at <anonymous> (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:2307:9)
    at unexpected (eval at <anonymous> (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:2313:9)
    at block_ (eval at <anonymous> (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:2708:28)
    at _function_body (eval at <anonymous> (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:2682:21)
    at function_ (eval at <anonymous> (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:2636:20)
    at expr_atom (eval at <anonymous> (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:2968:24)
    at maybe_unary (eval at <anonymous> (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:3303:19)`

**Comment by bravesomesh** [comment]
Not relevant to this project. Sorry I am closing this issue.
