### ISSUE TITLE
Unable to minify JavaScript (unexpected character @

### ISSUE THREAD

**Issue by francisrod01** [terinjokes/gulp-uglify#297]
I have a problem to minify vendor scripts. I think that error is caused by `angular-route` syntax.

~$ bower info angular-route

```
{
  name: 'angular-route',
  version: '1.6.4',
  license: 'MIT',
  main: './angular-route.js',
  ignore: [],
  dependencies: {
    angular: '1.6.4'
  },
  homepage: 'https://github.com/angular/bower-angular-route'
}
```

A part of gulpfile code:

```js
...

pipes.builtVendorScriptsProd = function () {
  return gulp.src(bowerFiles())
    .pipe(pipes.ordererVendorScripts())
    .pipe(plugins.concat('vendor.min.js'))
    .pipe(plugins.uglify().on('error', pipes.showErrors))
    .pipe(gulp.dest(paths.distScriptsProd))
}
```

- `pipes.ordererVendorScripts()` sort vendor scripts
- `showErrors` is a function to display erros on console.

 I compile and present errors below:
```
[Error] GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected character '@'
File: /home/paneladm/projects/website/bower_components/angular-route/vendor.min.js
Line: 49754
```

### Update 1 - change the order of implementation 

If I alter the order between `concat()` and `uglify()`, the error is below:

```
Caused by: SyntaxError: Unexpected character '@'
File: /home/paneladm/projects/website/bower_components/animate.css/animate.css
Line: 1
```

### Update 2 - Utilizing babel and babel-es2015

Was very hard to found this error!

I follow the tip of `superul` use on stackoverflow and I use `gulp-babel` and `babel-preset-es2015` dependencies to found what errors for. I change my gulpfile and I add babel implementation before `concat()`.

```js
.pipe(plugins.babel({presets: ['es2015']}))
```

And a bug was founded. See more in below:

```
[BABEL] Note: The code generator has deoptimised the styling of "/home/paneladm/projects/website/bower_components/angular/angular.js" as it exceeds the max of "500KB".

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
SyntaxError: /home/paneladm/projects/website/bower_components/animate.css/animate.css: Unexpected token (1:0)
> 1 | @charset "UTF-8";
    | ^
  2 | 
  3 | /*!
  4 |  * animate.css -http://daneden.me/animate
    at Parser.pp$5.raise (/home/paneladm/projects/website/node_modules/babylon/lib/index.js:4452:13)
    at Parser.pp.unexpected (/home/paneladm/projects/website/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$1.parseDecorator (/home/paneladm/projects/website/node_modules/babylon/lib/index.js:1939:10)
    at Parser.pp$1.parseDecorators (/home/paneladm/projects/website/node_modules/babylon/lib/index.js:1924:26)
    at Parser.pp$1.parseStatement (/home/paneladm/projects/website/node_modules/babylon/lib/index.js:1818:10)
    at Parser.pp$1.parseBlockBody (/home/paneladm/projects/website/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/home/paneladm/projects/website/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/home/paneladm/projects/website/node_modules/babylon/lib/index.js:1673:17)
    at parse (/home/paneladm/projects/website/node_modules/babylon/lib/index.js:7180:37)
    at File.parse (/home/paneladm/projects/website/node_modules/babel-core/lib/transformation/file/index.js:517:15)
```

**Comment by francisrod01** [comment]
I was reminded by the Babylon owner that a filter is missing to only identify JS.
https://github.com/babel/babylon/issues/546
