### ISSUE TITLE
Unable to load via gulp-uglify/composer for uglify-es

### ISSUE THREAD

**Issue by riegersn** [terinjokes/gulp-uglify#302]
```
var uglifyjs    = require('uglify-es'),
    composer    = require('gulp-uglify/composer'),
    sourcemaps  = require('gulp-sourcemaps'),
    plumber     = require('gulp-plumber'),
    minify      = composer(uglifyjs, console);
```

```
module.js:471
    throw err;
    ^

Error: Cannot find module 'gulp-uglify/composer'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/riegersn/Code/no-politics-fb/gulpfile.js:12:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by terinjokes** [comment]
You have to be using gulp-uglify version 3.0.0 or later.
