### ISSUE TITLE
Browserify bundle with sourcemaps causes  "Converting circular structure to JSON" exception

### ISSUE THREAD

**Issue by jurafa** [terinjokes/gulp-uglify#304]
When I try to run my browserify bundle with sourcemaps through uglify-es it end with '  TypeError: Converting circular structure to JSON' exception.

My gulpfile:
```
 var uglifyjs = require('uglify-es');
  var composer = require('gulp-uglify/composer');
  var uglify = composer(uglifyjs, console);
...
 appBundler.bundle()
                .on('error', gp.util.log)
                .pipe(source('source.js'))
                .pipe(buffer())
                .pipe(gp.concat('source.min.js'))
                .pipe(gp.if(!options.development,
                     pipe(
                         gp.sourcemaps.init({
                             loadMaps: true
                         }),
                         uglify({ compress: { sequences: false } }),
                         gp.sourcemaps.write('./',{sourceRoot:'./'}))))				
                .pipe(gulp.dest(options.dest))
```

StackTrace:
```
  TypeError: Converting circular structure to JSON
       at Object.stringify (native)
       at Object.toString (eval at <anonymous> (E:\WORK\RexHMI\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:11954:47)
       at Object.minify (eval at <anonymous> (E:\WORK\RexHMI\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:13047:56)
       at E:\WORK\RexHMI\node_modules\gulp-uglify\lib\minify.js:51:28
       at DestroyableTransform._transform (E:\WORK\RexHMI\node_modules\gulp-uglify\composer.js:10:23)
```

**Comment by terinjokes** [comment]
You should file a bug with the uglify-es team, I don't think that this is a bug here.

**Comment by jurafa** [comment]
You are right. I tried it directly with uglify-es and the bug is the same. Sorry.
