### ISSUE TITLE
Wrong minified code produced with conditional variable declaration

### ISSUE THREAD

**Issue by shaan1337** [terinjokes/gulp-uglify#350]
Version:  Latest (3.0.1)

The following code:
```
return t?(e={},e.whatever='hello'):(e={},e.whatever='hello');
```

is minified to:
```
return e.whatever=(e={},"hello")};
```

which throws an `e is undefined` error (`e` is being used before initialization to `{}`)

**Reproduction steps:**
1. Download and unpack [uglify-bug.zip](https://github.com/terinjokes/gulp-uglify/files/2748449/uglify-bug.zip)
2. `yarn install` (or npm install)
3. `gulp minify`

Run original file, there are no errors:
`node file.js`

Run minified file:
`node dist/file.js`

**Error is thrown:**
```
/home/shaan/.../file.js:1
(function (exports, require, module, __filename, __dirname) { test=function(t){var e;return e.whatever=(e={},"hello")},test(!0);
                                                                                                      ^

TypeError: Cannot set property 'whatever' of undefined
    at test (/home/shaan/.../uglify-bug/dist/file.js:1:103)
    at Object.<anonymous> (/home/shaan/.../uglify-bug/dist/file.js:1:120)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by terinjokes** [comment]
It looks like this bug is a regression from previous version of UglifyJS. It previously minified to code that works correctly:

```js
