### ISSUE TITLE
Support streaming

### ISSUE THREAD

**Issue by binarykitchen** [terinjokes/gulp-uglify#36]
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
[gulp] Error in plugin 'gulp-uglify': Streaming not supported
    at uglifyError (/home/michael.heuberger/binarykitchen/code/videomail.io/node_modules/gulp-uglify/lib/error.js:6:9)
    at Transform.minify [as _transform] (/home/michael.heuberger/binarykitchen/code/videomail.io/node_modules/gulp-uglify/index.js:18:20)
    at Transform._read (/home/michael.heuberger/binarykitchen/code/videomail.io/node_modules/gulp-uglify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/home/michael.heuberger/binarykitchen/code/videomail.io/node_modules/gulp-uglify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/michael.heuberger/binarykitchen/code/videomail.io/node_modules/gulp-uglify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:238:10)
    at writeOrBuffer (/home/michael.heuberger/binarykitchen/code/videomail.io/node_modules/gulp-uglify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:228:5)
    at Transform.Writable.write (/home/michael.heuberger/binarykitchen/code/videomail.io/node_modules/gulp-uglify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:195:11)
    at write (/home/michael.heuberger/binarykitchen/code/videomail.io/node_modules/vinyl-source-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:605:24)
    at flow (/home/michael.heuberger/binarykitchen/code/videomail.io/node_modules/vinyl-source-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:614:7)
    at Transform.pipeOnReadable (/home/michael.heuberger/binarykitchen/code/videomail.io/node_modules/vinyl-source-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:646:5)
```

I have to wrap your plugin with `streamify` to make it work :(

**Comment by StreetStrider** [comment]
Can somebody explain why thing like `vinyl-buffer` required?
My case: `browserify stream -> vinyl-source-stream -> gulp-uglify -> fail`.
As far as I understood `vinyl-source-stream` converts ordinary Node stream into gulp-like pseudo-files stream. So things like `gulp-uglify` should just work fine (as fine as they work with actual `gulp.src` emitted streams).
So why I need to put special `vinyl-buffer` after `vinyl-source-stream` to make things work?
