### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by asadkhan-dbz** [terinjokes/gulp-uglify#368]
at the time of compiling, facing this issue

`RangeError: Maximum call stack size exceeded
at Object.before (eval at (/Users/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:1:0), )
at AST_Node.eval [as transform] (eval at (/Users/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:1:0), :2902:35)
at eval (eval at (/Users/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:1:0), :3024:43)
at AST_Node.eval [as transform] (eval at (/Users/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:1:0), :2906:21)
at eval (eval at (/Users/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:1:0), :3037:31)
at AST_Node.eval [as transform] (eval at (/Users/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:1:0), :2906:21)
at eval (eval at (/Users/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:1:0), :3019:29)
at AST_Node.eval [as transform] (eval at (/Users/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:1:0), :2906:21)
at eval (eval at (/Users/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:1:0), :3020:29)
at AST_Node.eval [as transform] (eval at (/Users/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:1:0), :2906:21)

npm ERR! Darwin 20.6.0
npm ERR! argv "/Users/versions/node/v0.12.0/bin/node" "/Users/versions/node/v0.12.0/bin/npm" "run" "gulp"
npm ERR! node v0.12.0
npm ERR! npm v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! @1.0.0 gulp: gulp
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @1.0.0 gulp script 'gulp'.
npm ERR! This is most likely a problem with the package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! gulp
npm ERR! You can get their info via:
npm ERR! npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /Users/npm-debug.log`

Environment

Browser [Chrome Version 94.0.4606.71 (Official Build) (x86_64)]:
React-PDF version [2.5.3]:
React version [15.0.1]:
gulp version [3.9.0]:

**Comment by terinjokes** [comment]
There is not enough information provided to diagnose this.

**Comment by asadkhan-dbz** [comment]
> There is not enough information provided to diagnose this.

What else information you required, please let me know, I'll provide you
