### ISSUE TITLE
On JShint fail, Uglify throws errors.

### ISSUE THREAD

**Issue by markgoodyear** [terinjokes/gulp-uglify#5]
This is my set up currently (New to Gulp so I presume it's correct):

``` js
gulp.task('scripts', function() {
    gulp.src('./src/scripts/*.js', {ignore: ['vendor']})
        .pipe(jshint( fs.readFile('./.jshintrc') ))
        .pipe(jshint.reporter('default'))
        .pipe(concat('main.js'))
        .pipe(uglify()) 
        .pipe(gulp.dest('./dist/assets/js'));
});
```

It all works when there are no JShint errors, however when the task is ran and there is an error in the JS, I get this error:

```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error
    at new JS_Parse_Error (node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:196:18)
    at js_error (node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:204:11)
    at croak (node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:636:9)
    at token_error (node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:644:9)
    at unexpected (node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:650:9)
    at expr_atom (node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1131:9)
    at maybe_unary (node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1287:19)
    at expr_ops (node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1322:24)
    at maybe_conditional (node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1327:20)
    at maybe_assign (node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1351:20)
```

Is there any way to fix this issue? I presume it's an uglify issue as all the errors mention it.

Cheers
Mark

**Comment by dutronlabs** [comment]
@ionutvmi that worked perfectly. thanks!

**Comment by thom801** [comment]
I ended up having to go with https://www.npmjs.com/package/gulp-minify-css

**Comment by roeeyossef** [comment]
@ionutvmi Works Great !
