### ISSUE TITLE
it did not throw detail information when error occurs

### ISSUE THREAD

**Issue by xiaoji121** [terinjokes/gulp-uglify#50]
when js has syntax error， this plugin output nothing but error stack.

``` javascript
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error
    at new JS_Parse_Error (/Users/dongming/dev/gitlab/wrench/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:189:18)
    at js_error (/Users/dongming/dev/gitlab/wrench/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:197:11)
    at croak (/Users/dongming/dev/gitlab/wrench/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:656:9)
    at token_error (/Users/dongming/dev/gitlab/wrench/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:664:9)
    at unexpected (/Users/dongming/dev/gitlab/wrench/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:670:9)
    at /Users/dongming/dev/gitlab/wrench/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:754:17
    at /Users/dongming/dev/gitlab/wrench/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:703:24
    at block_ (/Users/dongming/dev/gitlab/wrench/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:977:20)
    at ctor.body (/Users/dongming/dev/gitlab/wrench/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:950:25)
    at function_ (/Users/dongming/dev/gitlab/wrench/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:955:15)
```

**Comment by ai** [comment]
Why not add this info to README.md?

**Comment by samvv** [comment]
Thanks, solved my issue as well.

**Comment by AliMD** [comment]
please update your read me

**Comment by terinjokes** [comment]
@AliMD The README on the 1.2.0 branch contains some documentation on errors.

**Comment by mprandot** [comment]
hello!

I use elixir + gulp, and i get the same error, someone can help me?
the function `uglify()` is show `ReferenceError: uglify is not defined`
```
var elixir = require('laravel-elixir');
var gutil = require('gulp-util');

elixir(function (mix) {

    mix.browserify('Vue/main.js');

    mix.styles([
        'bootstrap.min.css',
        'plugins.css',
        'main.css',
        'themes/passion.css',
        'themes.css',
        'rbr/customrbr.css',
        'rbr/details.css',
        'rbr/forms.css'
    ], 'public/css/layout-one.css');


    mix.scripts([
        'vendor/modernizr-2.8.3.min.js',
        'vendor/jquery-2.2.0.min.js',
        'vendor/bootstrap.min.js',

        '../../../node_modules/lodash/lodash.js',
        '../../../node_modules/moment/moment.js',
        '../../../node_modules/moment/locale/pt-br.js',

        'plugins.js',
        'app.js',
        'pages/uiTables.js',

    ], 'public/js/layout-one.js').pipe(uglify().on('error', gutil.log));

    mix.copy('resources/assets/css/fonts', 'public/build/css/fonts');
    mix.copy('resources/assets/css/themes', 'public/build/css/themes');
    mix.copy('resources/assets/fonts', 'public/build/fonts');
    mix.copy('resources/assets/img', 'public/build/img');
    mix.copy('resources/assets/images', 'public/images');
    mix.copy('resources/assets/js/pages', 'public/build/js/pages');
    mix.copy('resources/assets/js/plugins', 'public/build/js/plugins');
    mix.copy('resources/assets/js/vendor', 'public/build/js/vendor');

    mix.scripts([
        'rbr/Graphics/prospectionGraphics.js'
    ], 'public/js/graphics.js');

    mix.version([
        'css/layout-one.css',
        'js/layout-one.js',
        'js/graphics.js']);

});
```

**Comment by terinjokes** [comment]
@mprandot Please see the README for how the use the recommended `pump` module instead of using those `pipe` functions directly. Then you'll get the better error messages this module already has.

**Comment by mprandot** [comment]
@terinjokes  sorry!

I found the error, sintax error in one .js in `mix.scripts`

Thanks!

**Comment by mrbacay** [comment]
I'm having the same problem, and I've tried what @devdattaT suggested, but it's still giving me the same information. It stops at the error on events.js. 

Do I have to pass the error event to gutil.log?

**Comment by whoan** [comment]
The fastest solution I've found was to capture the error with this:

```javascript
process.on('uncaughtException', function(error) {
    console.log(error);
    process.exit(1)
})
```

I put that snippet in my **gulpfile.js** and I could figure it out where was the problem. It was a problem in my code.

**Comment by terinjokes** [comment]
If you use `pump` like the examples in the readme, errors will be
propagated to Gulp, which will format the errors correctly.
