### ISSUE TITLE
Uglify throws Parse error

### ISSUE THREAD

**Issue by rkmax** [terinjokes/gulp-uglify#76]
this is the error

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error
    at new JS_Parse_Error (/home/rkmax/my-project/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:189:18)
    at js_error (/home/rkmax/my-project/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:197:11)
    at croak (/home/rkmax/my-project/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:656:9)
    at token_error (/home/rkmax/my-project/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:664:9)
    at expect_token (/home/rkmax/my-project/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:677:9)
    at expect (/home/rkmax/my-project/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:680:36)
    at /home/rkmax/my-project/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1222:13
    at /home/rkmax/my-project/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:703:24
    at expr_atom (/home/rkmax/my-project/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1152:35)
    at maybe_unary (/home/rkmax/my-project/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1327:19)
    at expr_ops (/home/rkmax/my-project/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1362:24)
    at maybe_conditional (/home/rkmax/my-project/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1367:20)
    at maybe_assign (/home/rkmax/my-project/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1391:20)
    at expression (/home/rkmax/my-project/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1410:20)

```

this is my scripts task
```js
gulp.task('scripts', function() {

    var bundler = browserify({
        entries: ['./src/scripts/main.js'],
        debug: debug
    }).transform(stringify()); // the error persist even without this transformation

    bundler
        .bundle()
        .on('error', handleErrors)
        .pipe(source(getBundleName() + '.js'))
        .pipe(jshint())
        .pipe(jshint.reporter('default', { verbose: true }))
        .pipe(jshint.reporter('fail'))
        .pipe(buffer())
        .pipe(sourcemaps.init({loadMaps: true}))
        .pipe(uglify())
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest('./web/js'));
});
```js

**Comment by terinjokes** [comment]
@rkmax Are you using the latest version of this plugin? We now include the file that cased the parse error in the error message.

**Comment by rkmax** [comment]
no :( i see i'm using the 1.0.2, after the update the problem was solved. thanks for your help

**Comment by leaf-fly** [comment]
Excuse me,I also had a similar problem has been bothering me.
I'm just ready to use `gulp-uglify`.
To test the effect, then appear this mistake.
Now I can't use `gulp-uglify`!

Gulp task:
```javascript
var gulp = require('gulp');
var uglify = require('gulp-uglify');

gulp.task('minify', function () {
 gulp.src('js/*.js')
  .pipe(uglify())
  .pipe(gulp.dest('dist'));
});
```

Error:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error
    at new JS_Parse_Error (D:\gulp\node_modules\gulp-uglify\node_modules\uglify- js\lib\parse.js:189:18) 
    at js_error (D:\gulp\node_modules\gulp-uglify\node_modules\uglify-js\lib\par se.js:197:11) 
    at croak (D:\gulp\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse. js:657:9) 
    at token_error (D:\gulp\node_modules\gulp-uglify\node_modules\uglify-js\lib\ parse.js:665:9) 
    at expect_token (D:\gulp\node_modules\gulp-uglify\node_modules\uglify-js\lib \parse.js:678:9) 
    at expect (D:\gulp\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse .js:681:36) 
    at regular_for (D:\gulp\node_modules\gulp-uglify\node_modules\uglify-js\lib\ parse.js:909:9) 
    at for_ (D:\gulp\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.j s:901:16) 
    at D:\gulp\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:783: 24 
    at D:\gulp\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:704: 24
```

Environment:
`win7 x64`
`node v0.10.30`
`gulp-uglify v1.1.0`

**Comment by leaf-fly** [comment]
OK, I found the abnormal characters `&` in compressed file.It is ok to remove.

**Comment by IntellectProductions** [comment]
I'm getting this error. Running gulp yesterday worked perfectly fine, but this morning (changed NO code) and I'm getting this error.
```
$ gulp

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error
    at new JS_Parse_Error (C:\Source\Source2\bunny-meadows\node_modules\gulp-ugl
ify\node_modules\uglify-js\lib\parse.js:196:18)
    at js_error (C:\Source\Source2\bunny-meadows\node_modules\gulp-uglify\node_m
odules\uglify-js\lib\parse.js:204:11)
    at croak (C:\Source\Source2\bunny-meadows\node_modules\gulp-uglify\node_modu
les\uglify-js\lib\parse.js:675:9)
    at token_error (C:\Source\Source2\bunny-meadows\node_modules\gulp-uglify\nod
e_modules\uglify-js\lib\parse.js:683:9)
    at expect_token (C:\Source\Source2\bunny-meadows\node_modules\gulp-uglify\no
de_modules\uglify-js\lib\parse.js:696:9)
    at expect (C:\Source\Source2\bunny-meadows\node_modules\gulp-uglify\node_mod
ules\uglify-js\lib\parse.js:699:36)
    at function_ (C:\Source\Source2\bunny-meadows\node_modules\gulp-uglify\node_
modules\uglify-js\lib\parse.js:959:9)
    at expr_atom (C:\Source\Source2\bunny-meadows\node_modules\gulp-uglify\node_
modules\uglify-js\lib\parse.js:1188:24)
    at maybe_unary (C:\Source\Source2\bunny-meadows\node_modules\gulp-uglify\nod
e_modules\uglify-js\lib\parse.js:1358:19)
    at expr_ops (C:\Source\Source2\bunny-meadows\node_modules\gulp-uglify\node_m
odules\uglify-js\lib\parse.js:1393:24)
    at maybe_conditional (C:\Source\Source2\bunny-meadows\node_modules\gulp-ugli
fy\node_modules\uglify-js\lib\parse.js:1398:20)
    at maybe_assign (C:\Source\Source2\bunny-meadows\node_modules\gulp-uglify\no
de_modules\uglify-js\lib\parse.js:1422:20)
```

My gulpfile.js looks like this:

```
var gulp = require('gulp');

// Include Our Plugins
var concat = require('gulp-concat');
var uglify = require('gulp-uglify');
var rename = require('gulp-rename');
var livereload = require('gulp-livereload');

var paths = {
    // using framework version of jquery
    scripts: [
        'public/assets/js/jquery.min.js',
        'public/assets/plugins/mustachejs/mustache.js',
        'public/assets/js/modernizr.js',
        'public/assets/js/bootstrap.min.js',
        'public/assets/js/placeholders.min.js',
        'public/assets/plugins/bootstrap-wysiwyg/bootstrap3-wysihtml5.all.min.js',
        'public/assets/plugins/bootstrap-wysiwyg/bootstrap3-wysihtml5.min.js',
        'public/assets/plugins/responsiveslides/responsiveslides.min.js',
        'public/assets/plugins/bxslider/jquery.bxslider.min.js',
        'public/assets/plugins/magnific-popup/magnific-popup.js',
        'public/assets/js/jquery.autocomplete.min.js',
        'public/assets/js/plugins/additems.js',
        'public/assets/js/plugins/farm/farm.js',
        'public/assets/js/plugins/plusminus.js',
        'public/assets/js/core.js'
    ]
};

// Concatenate & Minify JS
gulp.task('scripts', function() {
    return gulp.src(paths.scripts)
        .pipe(concat('all.js'))
        .pipe(gulp.dest('public/assets/js'))
        .pipe(rename('all.min.js'))
        .pipe(uglify())
        .pipe(gulp.dest('public/assets/js'))
        .pipe(livereload());
});

// Watch Files For Changes
gulp.task('watch', function() {
	livereload.listen();
    gulp.watch(paths.scripts, ['scripts']);
});

// Default Task
gulp.task('default', ['scripts', 'watch']);
```

Again I didn't change anything so I don't get why all of a sudden this morning it doesn't want to work.

**Comment by IntellectProductions** [comment]
Following this helped:

1. Install Gulp-util
2. Import the Gulp-util by using the following statement: `var gutil = require('gulp-util');`
3. Finally, when you are uglifying the code, attach the error handler like this: `.pipe(uglify().on('error', gutil.log))`

I was able to debug it. It was a syntax error in one of the minified files I was including.

**Comment by SkeLLLa** [comment]
I've got similar bug with such simple code fragment:
```
var i;
function arr () { return [1,2,3] }
var a = arr();
for (i=0;i<a.length;a++){
   ...
}
```
And I was able to fix it with declaring new variable:
```
var i;
function arr () { return [1,2,3] }
var a = arr();
var aL = a.length;
for (i=0;i<a.length;a++){
   ...
}
```
So it seems that bug affects valid code. By the way all code of that js file was checked by jscs and there were no warnigns/errors.

**Comment by aaronharding** [comment]
Had the same too, it was a missing colon. Following @IntellectProductions 's solution helped with logging out to the command line :3

thanks!

**Comment by terinjokes** [comment]
@aaronharding You may prefer to read [combine streams to handle errors](https://github.com/gulpjs/gulp/blob/master/docs/recipes/combining-streams-to-handle-errors.md#combining-streams-to-handle-errors) from Gulp's documentation.

**Comment by sunnee5150** [comment]
having trouble pinpointing the location of the syntax error since app.min.js is not actually being created.  I also tried excluding maps (in case they were in the stream)

my task..
```
gulp.task('bundle-app', ['templates'], function() {
		return gulp.src(['src/app.js', 'src/**/*.js'])
			.pipe(sourcemaps.init())
				.pipe(concat('app.min.js'))
				.pipe(ignore.exclude(['**/*.map']))
				.pipe(uglify().on('error', gulpUtil.log))
			.pipe(sourcemaps.write('./'))
			.pipe(gulp.dest('./public/dist'));
	});
```
my error

```
[17:13:29] Using gulpfile ~/Desktop/PROJECTS/musicomp/gulpfile.js
[17:13:29] Starting 'templates'...
[17:13:29] Finished 'templates' after 140 ms
[17:13:29] Starting 'bundle-app'...
[17:13:29] { [Error: /Users/ernest son/Desktop/PROJECTS/musicomp/src/app.min.js: Unexpected token punc «;», expected punc «,»]
  message: '/Users/ernest son/Desktop/PROJECTS/musicomp/src/app.min.js: Unexpected token punc «;», expected punc «,»',
  fileName: '/Users/ernest son/Desktop/PROJECTS/musicomp/src/app.min.js',
  lineNumber: 42,
  stack: 'Error\n    at new JS_Parse_Error (/Users/ernest son/Desktop/PROJECTS/musicomp/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:196:18)\n    at js_error (/Users/ernest son/Desktop/PROJECTS/musicomp/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:204:11)\n    at croak (/Users/ernest son/Desktop/PROJECTS/musicomp/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:684:41)\n    at token_error (/Users/ernest son/Desktop/PROJECTS/musicomp/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:688:9)\n    at expect_token (/Users/ernest son/Desktop/PROJECTS/musicomp/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:701:9)\n    at expect (/Users/ernest son/Desktop/PROJECTS/musicomp/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:704:36)\n    at expr_list (/Users/ernest son/Desktop/PROJECTS/musicomp/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1207:44)\n    at /Users/ernest son/Desktop/PROJECTS/musicomp/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1222:23\n    at /Users/ernest son/Desktop/PROJECTS/musicomp/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:727:24\n    at expr_atom (/Users/ernest son/Desktop/PROJECTS/musicomp/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1185:35)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uglify' }
```

**Comment by terinjokes** [comment]
You can use `gulp.dest` multiple times, so you can save the intermediate "app.min.js" somewhere. In the following example, I save it to the "tmp/dist" folder.

```javascript
gulp.task('bundle-app', ['templates'], function() {
        return gulp.src(['src/app.js', 'src/**/*.js'])
            .pipe(sourcemaps.init())
                .pipe(concat('app.min.js'))
                .pipe(gulp.dest('tmp/dist'))
                .pipe(ignore.exclude(['**/*.map']))
                .pipe(uglify().on('error', gulpUtil.log))
            .pipe(sourcemaps.write('./'))
            .pipe(gulp.dest('./public/dist'));
    });
```

**Comment by aaronharding** [comment]
@sunnee5150 you are also running concat before uglify which is providing to be a disadvantage for you in this instance, since now your syntax error is in your concatenated file.

try and run uglify before concatenating and the error message will lead to you to the un-concatenated file and line number, making it easier to debug

@terinjokes ah thank you, i will look into it!

**Comment by sunnee5150** [comment]
thank you all, I'll try these ideas and report back!

**Comment by sunnee5150** [comment]
found the error and fixed by creating the concatenated file in tmp!

**Comment by ettachfn** [comment]
running into same issue. Have not tried the concatenated file in tmp folder but what do you look for in the js file

**Comment by sunnee5150** [comment]
modify your task just as Terinjokes shows above.  check the console for the exact location of your syntax error - voila!  syntax errors are typically typos.

**Comment by eqbalsajadi** [comment]
i figure out that uglify parser do not recognize character (`) that is useful for multiline html inline code

**Comment by McVanS** [comment]
Ran into the same problem and after two days discovered the problem. Turns out the error was not a typo but caused by "Unexpected token: operator (>)" and the code turned out to be: workingFiles.find(x => x.selectedFile == selectedFiles[i].name). I remove the > and the file passes. This is a problem. Is there any way to ignore this error?

**Comment by kyle-ssg** [comment]
In my case (probably others too), this was due to me accidentally writing es6 on an old project that still uses gulp 😅 .

@eqbalsajadi this is exactly the issue you're facing, inline templates are not natively supported.

If you wish to use features such as that I'd suggest you use babelify to transform js before uglifying.

My fix was to add the babilify transform (https://github.com/babel/babelify)
```
  var appBundler = browserify({
        entries: [options.src], // Only need initial file, browserify finds the rest
        transform: [
            [reactify, {}], [babelify, { presets: ["es2015", "react"] }],
        ],
        debug: options.development,
        cache: {},
        packageCache: {},
        fullPaths: options.development && !options.hot,
        plugin: options.development && options.hot ? [lrload] : [],
    });
```
