### ISSUE TITLE
Get error cannot find module 'gulp-uglify'

### ISSUE THREAD

**Issue by MARS1** [terinjokes/gulp-uglify#78]
Here is the error that i get, but before I paste that I've already done the following:

1) uninstalled package globally
2) tried re-installing package 
3) uglify NOT showing up in package.json which means it shouldn't even be looked at
4) removed .pipe(uglify()) from my compress/scripts gulp task function
5) finally reinstalled npm install --save-dev gulp-uglify and it saved to my package.json

Still get this error though

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error
    at new JS_Parse_Error (/Applications/AMPPS/www/SCC-blog/wp-content/themes/sccblog/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:189:18)
    at js_error (/Applications/AMPPS/www/SCC-blog/wp-content/themes/sccblog/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:197:11)
    at croak (/Applications/AMPPS/www/SCC-blog/wp-content/themes/sccblog/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:657:9)
    at token_error (/Applications/AMPPS/www/SCC-blog/wp-content/themes/sccblog/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:665:9)
    at unexpected (/Applications/AMPPS/www/SCC-blog/wp-content/themes/sccblog/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:671:9)
    at semicolon (/Applications/AMPPS/www/SCC-blog/wp-content/themes/sccblog/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:691:43)
    at /Applications/AMPPS/www/SCC-blog/wp-content/themes/sccblog/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:819:38
    at /Applications/AMPPS/www/SCC-blog/wp-content/themes/sccblog/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:704:24
    at block_ (/Applications/AMPPS/www/SCC-blog/wp-content/themes/sccblog/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:978:20)
    at ctor.body (/Applications/AMPPS/www/SCC-blog/wp-content/themes/sccblog/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:951:25)

**Comment by MARS1** [comment]
As you can see all the errors are coming from parse.js.

If i'm making a mistake I can't figure out where, and i've been using your package on other projects as well and have never encountered this problem.

**Comment by terinjokes** [comment]
@MARS1 the error you're getting comes from UglifyJS, a dependency of this module. It seemly means it can't parse the file you're giving as input: you might want to run `eslint` over it to figure out what's wrong.

Also, it looks like you might not be using the latest version of this project, 1.1.0, as we now include the file that failed to parse in the error message.

**Comment by MARS1** [comment]
@terinjokes thank you.
