### ISSUE TITLE
1.1.0 unhandled error

### ISSUE THREAD

**Issue by ilanbiala** [terinjokes/gulp-uglify#85]
```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error
    at new JS_Parse_Error (node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:189:18)
    at js_error (node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:197:11)
    at croak (node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:657:9)
    at token_error (node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:665:9)
    at unexpected (node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:671:9)
    at semicolon (node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:691:43)
    at simple_statement (node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:865:73)
    at node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:724:47
    at node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:704:24
    at block_ (node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:978:20)
```

**Comment by Varyampir** [comment]
+1

Rolling back to previous version of node or uglify does not solve the issues. This is on a Mac.

**Comment by jacqueslareau** [comment]
Are you using ES6 multi-line strings? It seems to do that with backticks. This plugins uses uglify-js in the back, so need to do further investigation.

**Comment by terinjokes** [comment]
What version of gulp-uglify are you using? In 1.1.0, all UglifyJS errors are caught and transformed into PluginErrors that include the filename that failed to minify in the error message.

**Comment by ilanbiala** [comment]
@terinjokes I wrote 1.1.0 because I'm using 1.1.0...@jacqueslareau I'm not using any ES6 code.

**Comment by jmar777** [comment]
Any updates on this? Kind of tough to go about debugging on a large code base if you don't know where to look...

**Comment by terinjokes** [comment]
@jmar777 I added some debugging stuff to the README while preparing for 1.2.0.

https://github.com/terinjokes/gulp-uglify/blob/4fa24c39bb74540da29d8d0fd1f98ca0bf947476/README.md

Please let me know if this did or did not help you in finding out where the problem lies. If it doesn't, I'd love to figure out some other way.

**Comment by white87332** [comment]
Sorry,  I have the same problem. 
I use version 1.2.
